solution
Artificial-Friend/jv-dao-annotation pull request #1
Opened 2021-01-11 18:13 UTC by Artificial-Friend

2021-01-11 18:18 UTC, Artificial-Friend commented
Don't mind Travis, he's on his path to evolve into a smart robot, but path is not yet completed, treat it with understanding.

2021-01-11 19:47 UTC, IwalkInSilence approved these changes

2021-01-11 19:47 UTC, IwalkInSilence commented on src/main/java/core/basesyntax/dao/DaoManufacturerImpl.java
> +        Storage.manufacturerId++;
Mentors told us that Storage must generate id, you can add method in storage that add id like a key and increace it, but it's up to you

2021-01-11 19:47 UTC, IwalkInSilence commented on src/main/java/core/basesyntax/model/Car.java
> +        id++;
same

2021-01-11 19:47 UTC, IwalkInSilence commented on src/main/java/core/basesyntax/model/Driver.java
> +        id++;
same

2021-01-11 19:47 UTC, IwalkInSilence commented on src/main/java/core/basesyntax/model/Manufacturer.java
> +        id++;
same

2021-01-12 07:59 UTC, Sofasmile requested changes

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/Main.java
> +        manufacturerService.update(manufacturer1);
what did we change in manufacturer1 objects?

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/dao/DaoManufacturerImpl.java
> +        Storage.manufacturers.put(Storage.generateId(), item);
let's create method save() in Storage class and use it here for generating and saving new data. example:
```
Storage.saveManufacturer(manufacturer); // this method will create id and call put() method from map
```

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/dao/DaoManufacturerImpl.java
> +        return Optional.of(Storage.manufacturers.get(id));
```suggestion
        return Optional.ofNullable(Storage.manufacturers.get(id));
```

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/dao/DaoManufacturerImpl.java
> +        // I get new value so I can't match it with old, what's the point?
you should replace the existing object in your storage with a new object from the input parameter.

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/dao/DaoManufacturerImpl.java
> +        return true;
we always return true. is it correct? What will be if there is no object in the map with input id?

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Car.java
> +        id++;
what is that? 
let's remove incrementation from here and `id` from input parameters in the constructor

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Car.java
> +    private static long id;
should this field be static?

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Car.java
> +    private static long id;
let's use Wrapper instead of primitive data type

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Driver.java
> +    private static long id;
the same here

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Manufacturer.java
> +    private static long id;
the same

2021-01-12 07:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/service/ManufacturerServiceImpl.java
> +    DaoManufacturer dao;
how about access modifier?

2021-01-12 09:50 UTC, Artificial-Friend commented
Thank you, now I get it.

2021-01-12 10:52 UTC, Sofasmile requested changes

2021-01-12 10:52 UTC, Sofasmile commented on src/main/java/core/basesyntax/db/Storage.java
> +        return Storage.manufacturers.get(id);
let's move this logic to dao layer

2021-01-12 10:52 UTC, Sofasmile commented on src/main/java/core/basesyntax/db/Storage.java
> +        return new ArrayList<>(Storage.manufacturers.values());
let's move this logic to dao layer

2021-01-12 10:52 UTC, Sofasmile commented on src/main/java/core/basesyntax/db/Storage.java
> +        Storage.manufacturers.remove(id);
let's move this logic to dao layer

2021-01-12 10:52 UTC, Sofasmile commented on src/main/java/core/basesyntax/db/Storage.java
> +    public static Manufacturer replace(Manufacturer manufacturer) {
let's move this logic to dao layer

2021-01-12 10:52 UTC, Sofasmile commented on src/main/java/core/basesyntax/db/Storage.java
> +        return oldVal;
we shouldn't return old value, let's return new

2021-01-12 12:10 UTC, Sofasmile requested changes
last comment

2021-01-12 12:10 UTC, Sofasmile commented on src/main/java/core/basesyntax/dao/DaoManufacturerImpl.java
> +        return get(id).isEmpty();
```suggestion
        if( Storage.manufacturers. containsKey(id)) {
                Storage.manufacturers.remove(id);
                return true;
        }
        return false;
```

2021-01-12 13:06 UTC, Sofasmile approved these changes

2021-01-12 13:26 UTC, merged