init
Artificial-Friend/jv-dao-annotation pull request #5
Opened 2021-01-19 15:50 UTC by Artificial-Friend

2021-01-19 16:44 UTC, Vedroid approved these changes

2021-01-20 07:11 UTC, boroda4436 requested changes

2021-01-20 07:11 UTC, boroda4436 commented on src/main/java/core/basesyntax/dao/DaoDriver.java
> +public interface DaoDriver extends DaoGenericInterface<Driver, Long> {
```suggestion
public interface DaoDriver extends GenericDao<Driver, Long> {
```
This is required by java naming convention to add an `Interface` word.

2021-01-20 09:58 UTC, boroda4436 approved these changes

2021-01-20 11:48 UTC, merged